language: cpp
dist: trusty
sudo: required


matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: COMPILER_CXX=g++-4.9 COMPILER_CC=gcc-4.9

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.6']
          packages: ['clang-3.6']
      env: 
	   - COMPILER_CXX=clang++-3.6 
	   - COMPILER_CC=clang-3.6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.9']
          packages: ['clang-3.9']
      env: COMPILER_CXX=clang++-3.9 COMPILER_CC=clang-3.9


script:
  - mkdir build && cd build
  - export CXX=$COMPILER_CXX
  - echo $CXX
  - export CC=$COMPILER_CC
  - echo $CC
  - cmake -DCMAKE_BUILD_TYPE=Release .. 
  - cmake --build .
