language: cpp
dist: precise
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.8']
      env: COMPILER_CXX=g++-4.8 COMPILER_CC=gcc-4.8

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env: COMPILER_CXX=clang++-3.6 COMPILER_CC=clang-3.6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.9', 'george-edison55-precise-backports']
          packages: ['clang-3.9', 'cmake', 'cmake-data']
      env: COMPILER_CXX=clang++-3.9 COMPILER_CC=clang-3.9

script:
  - mkdir build && cd build
  - export CXX=$COMPILER_CXX
  - export CC=$COMPILER_CC
  - cmake -DCMAKE_BUILD_TYPE=Release .. 
  - cmake --build .
