language: cpp
osx_image: xcode8.2
dist: precise
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: _CC=gcc-6 _CXX=g++-6 _DESC=// GCC 6.2

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.9']
          packages: ['clang-3.9']
      env: _CC=clang-3.9 _CXX=clang++-3.9 _DESC=// Clang 3.9

    - os: osx
      compiler: clang
      env: _CC=clang _CXX=clang++ _DESC=// Apple LLVM 8.0

script:
  - mkdir build && cd build
  - export CC=$_CC
  - export CXX=$_CXX
  - cmake -DCMAKE_BUILD_TYPE=Release .. 
  - cmake --build .
